### ISSUE TITLE
Does the SN persist after reboot? Does it change SN for UF-Instant?

### ISSUE THREAD

**Issue by Shto1337** [Unifi-Tools/UFiber.Configurator#1]
Hello,

I have 2 questions(not quite issues):

1. I have a UF-Nano-G, currently replacing a Huawei router(HG8247H). Does this tool modify the GPON Serial Number for the UF-Nano-G so that it persists after reboot?

2. Can the tool change the SN for UF-Instant while connected to an ER-X SFP? I am willing to test this out :)

Thank you

**Comment by galvesribeiro** [comment]
Hello!

> I have a UF-Nano-G, currently replacing a Huawei router(HG8247H). Does this tool modify the GPON Serial Number for the UF-Nano-G so that it persists after reboot?

Yes, it patches one of the partitions which holds that data. 

If you pass the `--vendor HWTC` and `--serial XXXXXXXXXX` (replace with your serial) it will be persistent across reboots for sure 😄. In fact all settings you do with this too is persistent and a backup of the original partition is kept local on the `dumps` directory from where you ran the tool.

> Can the tool change the SN for UF-Instant while connected to an ER-X SFP? I am willing to test this out :)

I've tested the tool against a firmware dump from UF-Instant that I've got from the internet. I'm waiting the real device to arrive Today or Tomorrow so I can test on a real one. 

Can you try run the tool with the `--dry-run` option as if you would replace the others to replace the serial number? 

That will basically run all the processes and will print some information on your terminal without actually changing the device. 

If you can print the output here would be awesome! 😄 

Thank you!

**Comment by Shto1337** [comment]
Hello,

> If you pass the --vendor HWTC and --serial XXXXXXXXXX (replace with your serial) it will be persistent across reboots for sure 😄. In fact all settings you do with this too is persistent and a backup of the original partition is kept local on the dumps directory from where you ran the tool.

I've just tried this, it doesn't work because my serial is 16 characters. For example, I do this manually by connecting to the ufiber and using the commands:

`ssh ubnt@192.168.9.2

> sh

# cd bin
# ./gponctl stop

Stop ONU without sending dying gasp messages

# ./gponctl setSnPwd --sn 12-34-56-78-90-12-34-56

======== Serial Number & Password ========

Serial Number: 12-34-56-78-90-12-34-56
Password : 20-20-20-20-20-20-20-20-20-20

==========================================

# ./gponctl init
# ./gponctl start

Start ONU with operational state: INIT (01)

# ./gponctl getSnPwd

======== Serial Number & Password ========

Serial Number: 41-4C-43-4C-xx-xx-xx-xx
Password : 20-20-20-20-20-20-20-20-20-20`

Below you can find the error using your tool:

`C:\Users\DD\Desktop\win-x64>UFiber.Configurator --host 192.168.9.2 --user ubnt --pw mypw --port 2222 --dry-run --vendor HWTC --serial 12-34-56-78-90-12-34-56
### Original Image ###
--- NVRAM Information --
- mtdblock3 hash: d79b72526c6f808fe85fda604565a80bb6cc2002bb1f5f6a21d504296b59fc9e
- NVRAM Version: 6
- Boot parameters: e=192.168.1.1:ffffff00 h=192.168.1.254 g= r=f f=vmlinux i=bcm963xx_fs_kernel d=1 p=0 c= a=
- Board Id: UBNT_SFU
- PSI size: 24
- Total MAC addresses: 5
- GPON MAC address: 18:E8:29:F0:D4:BD
- GPON Vendor Id: UBNT
- GPON Serial Number: 59a19d79
- GPON SLID (password):
- Checksum: 3126364939

### Patching fw-26042021-073053.bin...
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'serialNumber')
   at UFiber.Configurator.NVRAM.SetGponSerialNumber(ReadOnlySpan`1 serialNumber)
   at UFiber.Configurator.NVRAM.SetGponSerialNumber(String serialNumber)
   at <Program>$.<>c.<<Main>$>b__0_2(String host, String user, String pw, Int32 port, Boolean dryRun, String slid, String vendor, String serial, String mac)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
`

What am I doing wrong? Or  does the tool only allows 8 character serial...? Or should I replace the parameter --serial with --plid?

> Can you try run the tool with the --dry-run option as if you would replace the others to replace the serial number?
I will also order an UF-Instant and it should come next week. Will test it out.

> Btw, out of curiosity, where did you found this repo?
https://community.ui.com/questions/Unofficially-support-3rd-party-OLTs-ONT-Serial-Number-Configuration-Serial-Changing/989b2134-f3b4-498a-a76f-b50a199b752e#answer/b7d57ab5-69f7-4c69-8190-a200dd238f5a

Thank you

**Comment by galvesribeiro** [comment]
Hello!

I've just merged #3 which allow the HEX SLID and Serial numbers.

Please download the release [0.1.1](https://github.com/Unifi-Tools/UFiber.Configurator/releases/tag/v0.1.1) which will allow that.

There wasn't actually a bug. When you have 16 HEX characters like on your case, the first 4 bytes (8 characters), is the VendorID which in your case is ALCL (Alcatel). The remaining 4 bytes are the actual serial number. 

I've updated that `--serial` to accept 16 characters with the `-` and internally it will set the VendorID and the Serial at the same time so if you use a 16 characters long serial, you don't need to set the `--vendor` since it will be overwritten anyway.

Please let me know if it works.

I hope it helps, thanks for the report!

**Comment by Shto1337** [comment]
Hello,

Thank you very much for the patch! I will test it out tomorrow first thing and will reply if it worked.

**Comment by Shto1337** [comment]
it worked! but I had to pass the --vendor parameter. (serial and 

`C:\Users\DD\Desktop\win-x64>UFiber.Configurator --host 192.168.9.2 --user ubnt --pw mypw --port 2222  --serial 12-34-56-78-90-12-34-56
### Original Image ###
--- NVRAM Information --
- mtdblock3 hash: d79b72526c6f808fe85fda604565a80bb6cc2002bb1f5f6a21d504296b59fc9e
- NVRAM Version: 6
- Boot parameters: e=192.168.1.1:ffffff00 h=192.168.1.254 g= r=f f=vmlinux i=bcm963xx_fs_kernel d=1 p=0 c= a=
- Board Id: UBNT_SFU
- PSI size: 24
- Total MAC addresses: 5
- GPON MAC address:  redacted
- GPON Vendor Id: UBNT
- GPON Serial Number: 59a19d79
- GPON SLID (password):
- Checksum: 3126364939

### Patching fw-27042021-084832.bin...
To set the GPON Serial Number, you must pass both --vendor and --serial

C:\Users\DD\Desktop\win-x64>UFiber.Configurator --host 192.168.9.2 --user ubnt --pw R9(kj)-Fiber --port 2222 --serial 12-34-56-78-90-12-34-56 --vendor ALCL
### Original Image ###
--- NVRAM Information --
- mtdblock3 hash: d79b72526c6f808fe85fda604565a80bb6cc2002bb1f5f6a21d504296b59fc9e
- NVRAM Version: 6
- Boot parameters: e=192.168.1.1:ffffff00 h=192.168.1.254 g= r=f f=vmlinux i=bcm963xx_fs_kernel d=1 p=0 c= a=
- Board Id: UBNT_SFU
- PSI size: 24
- Total MAC addresses: 5
- GPON MAC address: redacted
- GPON Vendor Id: UBNT
- GPON Serial Number: 59a19d79
- GPON SLID (password):
- Checksum: 3126364939

### Patching fw-27042021-084904.bin...
### Patched fw-27042021-084904.bin!
--- NVRAM Information --
- mtdblock3 hash: 068b905195aac9821e0ce48b883546de3f03cdfacc421344ee5950599ad1fe94
- NVRAM Version: 6
- Boot parameters: e=192.168.1.1:ffffff00 h=192.168.1.254 g= r=f f=vmlinux i=bcm963xx_fs_kernel d=1 p=0 c= a=
- Board Id: UBNT_SFU
- PSI size: 24
- Total MAC addresses: 5
- GPON MAC address: 18:E8:29:F0:D4:BD
- GPON Vendor Id: HWTC
- GPON Serial Number: 59A19D79
- GPON SLID (password):
- Checksum: 2696680764

Uploading patched file to the target UFiber device...
Uploaded!
### Applying patched file on the target UFiber device...
### Applied patch! Please reboot your UFiber device to load the new image.`

It reboots and the SN persists! Thank you

**Comment by galvesribeiro** [comment]
I'm glad it worked! 

> but I had to pass the --vendor parameter.

Ops! My bad! When I've updated to support the HEX serial, I forgot to adjust the validation that was once requiring both to be filled.

Please check the release [0.1.2](https://github.com/Unifi-Tools/UFiber.Configurator/releases/tag/v0.1.2) which includes the fix. If you pass the `--vendor`, then it requires the `--serial`. If you pass just the `--serial` it is expected to be an HEX like on your case, so the `--vendor` is ignored. Thanks for reporting that!

Btw, was that the UF-Nano-G or UF-Instant?

Thank you!

**Comment by Shto1337** [comment]
It was UF-Nano-G

**Comment by kautzy** [comment]
hello,

got an ufiber instant module here... just wondering how you would patch the firmware on that one... seems like your tool needs to connect to the device with ssh, but i think ssh isn't available on the ufiber instant...? can you elaborate a bit on how to adjust the serial configuration on the ufiber instant?

thank you :)

**Comment by galvesribeiro** [comment]
@kautzy yes, we do use SSH but the tool isn't yet with the changes for the `UF-Instant` as we are still testing the possibilities.

We will update with a new release once a solution comes up.

**Comment by galvesribeiro** [comment]
I’m about to receive the CarlitoxxPro device. Any guidance on how to dump the firmware?

Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by galvesribeiro** [comment]
I think CarlitoxxPro v2 is the one which has the same hardware (Realtek IIRC)...

**Comment by galvesribeiro** [comment]
Just got an email from them with the "instructions manual"...
[CPGOS03-0490v2_Configuration-Manual.pdf](https://github.com/Unifi-Tools/UFiber.Configurator/files/6462913/CPGOS03-0490v2_Configuration-Manual.pdf)

From the telnet CLI it indeed is the same Realtek firmware which UF-Instant uses @obenturk except that they add and customize the RDK default admin pages which Ubiquiti deliberately removed. I've dig on the UF-Instant files and the web server settings still there and can be enabled, but there are no pages so it won't work anyway...

**Comment by galvesribeiro** [comment]
@obenturk 

> I changed them but my ISP kicked me out even with original isp ont so I left this modification.

You mean you were able to change it permanently as in it survive after reboot? 

When I plug my fiber, even if I don't change anything, it just reboot my device even my ISP being OK with it and giving me `O5`....

**Comment by obenturk** [comment]
With original firmware I can get O5 state but since serial number & MAC is different than ISP ONT, when I check ONUID which was given by OLT was showing 65 instead of 5.

After I change omci_app with V2801F, I can see correct serial number with top command (omci_app sould show serial number). Than I realized that I triggered an alarm at OLT side and I even could not use ISP provided ONT anymore.

ISP tech came and replaced Ericsson T63 ONT with SERCOMM one very very small footprint but it has modified firmware to work with Ericsson omci protocol.

I am waiting to find a carlitoxx v2 full flash dump to check if it will be work better or not.

By the way does anyone know a SFP stick that is suitable to Ericsson environment?

Thanks.

**Comment by obenturk** [comment]
Connect via uart pins and boot into uboot than you can dump whole flash.

**Comment by galvesribeiro** [comment]
I got my CarlitoxxPro, but it doesn't even work properly when connect to UDM-Pro or Unifi Switch Pro 24P. When plugged on the SFP, it just doesn't do anything. Even its IP address is not accessible...

**Comment by pmgcosta** [comment]
Can you check that: https://community.ui.com/questions/UDM-PRO-GPON-SFP-CarlitoxxPro-CPGOS03-0490-v2-0/362172d4-8a5f-4bda-a841-4a34c075c57f

**Comment by galvesribeiro** [comment]
@pmgcosta yup, already had. Check the last comment which is mine.

BTW, CarlitoxxPro support is pretty bad... Its almost a week since I asked for help and they don't reply emails...

**Comment by pmgcosta** [comment]
I'm in the same boat with an UDM-PRO and UF-Instant without any joy, i
think next i will try to buy one AFM0002TIM or MA5671A

**Comment by jjeziorny** [comment]
I have two AFM0002TIM @pmgcosta which I bought quite cheap on ebay, both working fine on UB edgerouter.
One internet connection is fully working (Moviestar network) but the second won't acquire DHCP IP (Orange network), still trying to work through that, some french posts say Orange used DHCP authentication and I need a fti/ password which so far I could not get it anywhere.

**Comment by galvesribeiro** [comment]
@obenturk if you can show us the steps and requirements for dumping the CarlitoxxPro FW it would be great. 

I'm not an electrical/mechanical engineer like you, but if you give me the steps, I can put together a raspberry Pi and solder the pins on the SFP PCB if you point the directions in order to connect to it. I don't even know how to open the SFP o.O. How to do that?

Also, assuming you share the steps, and I successfully can dump the files, what exactly do you want me to dump that would help you load a custom firmware on UF-Instant?

Thanks in advance. It would be really great if we can figure that out so we can incorporate this to UFiber.Configurator.

**Comment by pmgcosta** [comment]
Juliano, can you explain how to access to the AFM0002TIM default ip and
user and password ?

**Comment by pmgcosta** [comment]
> I have two AFM0002TIM @pmgcosta which I bought quite cheap on ebay, both working fine on UB edgerouter.
> One internet connection is fully working (Moviestar network) but the second won't acquire DHCP IP (Orange network), still trying to work through that, some french posts say Orange used DHCP authentication and I need a fti/ password which so far I could not get it anywhere.

Can you explain how to access to the AFM0002TIM default ip and
user and password ?

**Comment by jjeziorny** [comment]
> > I have two AFM0002TIM @pmgcosta which I bought quite cheap on ebay, both working fine on UB edgerouter.
> > One internet connection is fully working (Moviestar network) but the second won't acquire DHCP IP (Orange network), still trying to work through that, some french posts say Orange used DHCP authentication and I need a fti/ password which so far I could not get it anywhere.
> 
> Can you explain how to access to the AFM0002TIM default ip and
> user and password ?

Default IP (if memory serves me well) is 192.168.1.1/24, so you can configure your router SFP interface with an IP on that range (I used 192.168.1.2/30 as my network is 1.1 already), then telnet (no password) or SSH with admin/system to it.

This device has no vi/vim, so for editing the config I copied it locally, edited and pushed back. 
```
ssh admin@192.168.1.1 "cat /var/config/lastgood.xml" > lastgood.xml
ssh admin@192.168.1.1 "cat /var/config/lastgood_hs.xml" > lastgood_hs.xml
```
Then edit and upload again
```
cat lastgood.xml | ssh admin@192.168.1.1 -T "cat > /var/config/lastgood.xml"
cat lastgood_hs.xml | ssh admin@192.168.1.1 -T "cat > /var/config/lastgood_hs.xml"
```

I recommend loging into the device again after this and checking the config files are OK before rebooting it. If for any reason you lock yourself out by messing up the IP, these devices also have a secondary IP on VLAN2
```
2: br0.2@br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether ac:4a:fe:98:0a:f2 brd ff:ff:ff:ff:ff:ff
    inet 192.168.10.1/24 brd 192.168.10.255 scope global br0.2
```

**Comment by pmgcosta** [comment]
Welcome to UniFi Dream Machine!
# ifconfig eth9:2 192.168.1.2 netmask 255.255.255.252 up
# telnet 192.168.1.1

telnet: can't connect to remote host (192.168.1.1): No route to host

**Comment by pmgcosta** [comment]
Forget, i tried the secondary ip and works thanks, that me try now change the serial and password

# ifconfig eth9:2 192.168.2.2 netmask 255.255.255.252 up
# telnet 192.168.2.1
Connected to 192.168.2.1

Entering character mode
Escape character is '^]'.

**Comment by pmgcosta** [comment]
<Value Name="WAN_MODE" Value="7"/>
  <Value Name="LAN_IP_ADDR" Value="192.168.2.1"/>
  <Value Name="LAN_SUBNET" Value="255.255.255.0"/>
  <Value Name="LAN_ENABLE_IP2" Value="0"/>
  <Value Name="LAN_IP_ADDR2" Value="192.168.100.1"/>
  <Value Name="LAN_SUBNET2" Value="255.255.255.0"/>

**Comment by pmgcosta** [comment]
<Value Name="WAN_MODE" Value="7"/>
  <Value Name="LAN_IP_ADDR" Value="192.168.2.1"/>
  <Value Name="LAN_SUBNET" Value="255.255.255.0"/>
  <Value Name="LAN_ENABLE_IP2" Value="0"/>
  <Value Name="LAN_IP_ADDR2" Value="192.168.100.1"/>
  <Value Name="LAN_SUBNET2" Value="255.255.255.0"/>

**Comment by pmgcosta** [comment]
Is the right place to change ?


lastgood
`  <Value Name="GPON_PLOAM_PASSWD" Value="1234567890"/>`

lastgood_hs
`  <Value Name="GPON_SN" Value="TNBB7BAB2B78"/> `

**Comment by jjeziorny** [comment]
> Is the right place to change ?
> 
> lastgood
> ` <Value Name="GPON_PLOAM_PASSWD" Value="1234567890"/>`
> 
> lastgood_hs
> ` <Value Name="GPON_SN" Value="PTIN91194A08"/>`
> 
> But when i check the serialnumber:
> 
> ```
> # omcicli get sn
> SerialNumber: PTINffffff91194a08
> ```
> 
> I got this mess with ffff in the midle how can i fix that ?
> 
> My serial number is : 5054494E91194A08 (PTIN91194A08)
> 
> But appear that the serialnumber can't not start with 9 why ? with 7 works
> 
> ```
> omcicli set sn PTIN, 71194A08
> omcicli get sn
> SerialNumber: PTIN71194a08
> ```
> 
> ```
> omcicli set sn PTIN, 91194A08
> omcicli get sn;
> SerialNumber: PTINffffff91194a08
> ```
> 
> Is that normal how can i fix that ?

I don't think that's a problem, just checked mine and the output of `# omcicli get sn` also shows ffff in some places.
```
# omcicli get sn
SerialNumber: HWTC3cffffff9a1dffffffa3
```

What provider are u using?  Did you check the onu-state to see if it got O5 ?
```
# diag
RTK.0> gpon get onu-state
ONU state: Operation State(O5) 
```

Once in state O5 you should see the flows have been created
```
RTK.0> gpon show ds-flow 
============================================================
     GPON ONU MAC D/S Flow Status
Flow ID | GEM Port | Type | Multicast | AES
      0 |     2047 |  ETH |         * |    
      1 |      278 |  ETH |           |   *
      2 |      279 |  ETH |           |   *
      3 |      280 |  ETH |           |   *
     32 |       10 | OMCI |           |   *
============================================================
```

Once the flows are created you should be able to acquire an IP via DHCP or PPPoE, depending on what your provider uses.

**Comment by pmgcosta** [comment]
Yes i'm on O5 state but without internet on my dream machine:


```
# diag
RTK.0> gpon get onu-state
ONU state: Operation State(O5)
RTK.0>
RTK.0> gpon show ds-flow
============================================================
     GPON ONU MAC D/S Flow Status
Flow ID | GEM Port | Type | Multicast | AES
      0 |     4095 |  ETH |           |
     32 |       45 | OMCI |           |
============================================================
RTK.0>
```


```
Deam machine
# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNO                                                                                                                                                             WN qlen 1000
    link/ether ac:4a:fe:7b:2c:78 brd ff:ff:ff:ff:ff:ff
3: eth0.2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 00:00:00:01:00:02 brd ff:ff:ff:ff:ff:ff
4: nas0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNO                                                                                                                                                             WN qlen 1000
    link/ether 00:00:00:01:00:02 brd ff:ff:ff:ff:ff:ff
5: pon0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNO                                                                                                                                                             WN qlen 1000
    link/ether 00:00:00:01:00:02 brd ff:ff:ff:ff:ff:ff
6: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN
    link/ether ac:4a:fe:7b:2c:78 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.1/24 brd 192.168.2.255 scope global br0
7: nas0_0: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN qlen                                                                                                                                                              10
    link/ether ac:4a:fe:7b:2c:7b brd ff:ff:ff:ff:ff:ff
8: br0.2@br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether ac:4a:fe:7b:2c:78 brd ff:ff:ff:ff:ff:ff
    inet 192.168.10.1/24 brd 192.168.10.255 scope global br0.2


```

**Comment by jjeziorny** [comment]
Deam machine is the SFP I assume (the output looks like it's from it)

The SFP won't pick an IP, they work as bridge by default, you need to configure the correct VLAN on the SFP port in your router to get the IP (DHCP or PPPoE).

In my edgerouter for example
with pppoe
```
# show interfaces ethernet eth11        
 address 192.168.2.2/30
 duplex auto
 speed auto
 vif 20 {
     pppoe 1 {
         default-route force
         description DIGI
         firewall {
             in {
                 name WAN_IN
             }
             local {
                 name WAN_LOCAL
             }
         }
         mtu 1492
         name-server auto
         password xxxxx
         user-id yyyyy
     }
 }
```
with DHCP
```
# show interfaces ethernet eth8 
 address 192.168.254.254/30
 description Admin
 duplex auto
 speed auto
 vif 832 {
     address dhcp
     description Republica
     dhcp-options {
         default-route-distance 200
     }
     firewall {
         in {
             name WAN_IN
         }
         local {
             name WAN_LOCAL
         }
     }
 }
```

**Comment by jjeziorny** [comment]
btw, this conversation is way of topic here.... we should have it somewhere else.
feel free to use this thread on the mikrotik forum (most of what I mentioned here I already posted there also)
https://forum.mikrotik.com/viewtopic.php?f=3&t=116364&start=300

**Comment by pmgcosta** [comment]
Posted! in forum,

@galvesribeiro  any news regarding uf-instant and CarlitoxxPro-CPGOS03-0490-v2 ?

**Comment by galvesribeiro** [comment]
Not yet. I'm trying to dump the firmware. Will update once I have more news.

**Comment by obenturk** [comment]
@galvesribeiro Hi any new about dumping the firmware?

**Comment by galvesribeiro** [comment]
Hello @obenturk no, I wasn't able to disassembly mine. I only have one CarlitoxxPro and it is running my internet. I'm afraid I'll brick it due to lack of soldering skills and will have to wait months to have a replacement arrive.

Any other alternative to pull the firmware files besides soldering?

**Comment by danielducu** [comment]
Any news on the uf-instant ?

**Comment by kautzy** [comment]
> Any news on the uf-instant ?

hm, i'd be interested in that one too... :)

**Comment by galvesribeiro** [comment]
Not yet :/ We are still unable to write to the partitions of the UF-Instant as of Today. Still trying workarounds.

**Comment by galvesribeiro** [comment]
@obenturk have you seen this: https://github.com/Anime4000/RTL9601C1/issues/2#issuecomment-900913125 ?

Also, I could sponsor you to make you find time if you made it work.

**Comment by obenturk** [comment]
Hello,

If someone dump whole flash of carlitoxx pro. (Need to do that to get rid out ui's multiple ser# &mac protection) I can write it on uf instant. Currently I have original uf-instant firmware and I am able to load different firmwares and revert back to original.

What I know is carlitoxxpro has the best firmware.

**Comment by galvesribeiro** [comment]
AHHH ok. Sorry, I misunderstood. I Thought you wanted the UF-Instant Firmware. 

Ok, so @obenturk  can you show the steps to extract the firmware from it?

**Comment by Danno88-88** [comment]
Hi, do someone have news about UF-Instant, configurator or flashing Carlioxxpro firm?

**Comment by mangod18** [comment]
Hi All, 
Long time no updates here. Browsing many websites I found one great repo https://github.com/Anime4000/RTL960x/
Many useful information and recommendation which one SFP stick you should buy. By the way the same repo took me to the next one you might be interested in https://github.com/stich86/UF-Instant-Mod. This one contains information how to upgrade rootFS in UF-Instant and there is also some custom rootfs available (you can download it) which I believe has SN/PLOAM change capability.

I didn't test it yet because my UF-Instant in being delivered to me. I can test and provide with result maybe next weekend. To  all UF-Instant owners, you can check it and let us know in the meantime how it works. Good luck.

**Comment by m0veax** [comment]
I will try the mentioned firmware on an UFiber-Instant in the next few weeks.

Will report my results here afterwards.

**Comment by m0veax** [comment]
Hey, i tried the custom rootfs and the SN and stuff persists after reboot. Do you need any further informations? We will try the UFiber-Instant soon and I will provide informations if the ISP accepted it

**Comment by m0veax** [comment]
Hey,

I just realized, that the mtd3 partition is a mountable JFFS2. After mounting it, you can fiddle around in the xml files and persist the data there. I found my original serialnumber in those XML Files.

This tool here is patching on binary level, but for the UFiber-Instant it seems like the offsets aren't correct.

I have not tried this, but maybe changing the device name ect in the XML files and persisting the JFFS2 could result in getting the target serial number on the device after flashing it back to `/dev/mtd3`.

I can't test this by myself anymore, since i gave the Hardware back to his owner after getting a persisted SN using https://github.com/stich86/UF-Instant-Mod. But maybe this helps someone seeking a solution without using a modified rootfs.

**Comment by m0veax** [comment]
Update on this. I got the hardware back, the Dream Machine didnt recognized the new configured SN and VendorID. I will give you an update after I investigated this.

**Comment by AyberkAltuntop** [comment]
> Update on this. I got the hardware back, the Dream Machine didnt recognized the new configured SN and VendorID. I will give you an update after I investigated this.

Hello, any update?

**Comment by m0veax** [comment]
Hey, I don't own a dream machine, so it is hard to try it.

I'll get in touch with my colleague who has a dream machine and try to find an appointment to try different things.

**Comment by AyberkAltuntop** [comment]
I tried something with UF-Instant-Mod, but why the changes I made are not permanent. I have an issue, can you help me with this please? Thanks a lot.

https://github.com/stich86/UF-Instant-Mod/issues/21

**Comment by fabioneves** [comment]
@pmgcosta @galvesribeiro hello!
did you manage to replace MEO Fibergateway with Ubiquiti Nano G or Loco ONT's? I wanted to replace everything with a new Ubiquit ONT + Router, but looks like replacing the ONT might be a challenge.
