### ISSUE TITLE
UFiber WiFi

### ISSUE THREAD

**Issue by FloraNuno** [Unifi-Tools/UFiber.Configurator#7]
Does this work in the UFiber WiFi, I have 1,5G connection and the router I have limits me to 1(rj45) 1Gb port, if i can change the serial and password I can use all 4 ports not limiting me to 1 port.

**Comment by galvesribeiro** [comment]
Hi!

I don't have one here but it should work as expected since it shares the same bits as UF-Loco and UF-Nano-G. 

Run the tool with the `--dry-run` and you should see if it was able to run and patch your firmware locally without having to write it to the device.

**Comment by ChristianOrrala** [comment]
Hi @galvesribeiro thanks for the awesome work!!!

I have one UF-WIFI and sadly it doesn't work, are you planning to support it? if so how can I help you?

Thank you again.

Here it's the error:

```
nhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Invalid data, CRC doesn't match
   at UFiber.Configurator.NVRAM..ctor(ReadOnlySpan`1 data, UInt32 offset, UInt32 length)
   at <Program>$.<>c.<<Main>$>b__0_2(String host, String user, String pw, Int32 port, Boolean dryRun, String slid, String vendor, String serial, String mac, String fwToRestore)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
````

**Comment by mjrr15** [comment]
Same error here.

Device Model: UFiber WiFi
Firmware Version: v4.3.1

Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Invalid data, CRC doesn't match
   at UFiber.Configurator.NVRAM..ctor(ReadOnlySpan`1 data, UInt32 offset, UInt32 length)
   at <Program>$.<>c.<<Main>$>b__0_2(String host, String user, String pw, Int32 port, Boolean dryRun, String slid, String vendor, String serial, String mac, String fwToRestore)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()

**Comment by mjrr15** [comment]
@galvesribeiro  If it helps, here is a dump of the NVRAM values when running on the UFiber WIFI.

Version:36
BootLine:00-00-FF-FF-16-A9-20-DB-3D-7E-81-25-3D-22-57-4C-41-4E-5F-51-4F-53-5F-53-54-41-5F-54-42-4C-22-3E-20-3C-21-2D-2D-69-6E-64-65-78-3D-32-2D-2D-3E-0A-19-85-C0-02-00-00-02-AD-4F-0F-1A-60-00-00-00-05-00-00-00-D4-00-00-81-A4-00-00-00-00-00-00-3F-F9-00-00-00-0B-00-00-00-0B-00-00-00-0B-00-00-30-24-00-00-02-69-00-00-0F-D5-06-00-FF-FF-18-FE-38-AD-69-4B-E5-BF-78-5E-DC-96-5D-6F-82-30-14-86-EF-F7-2B-18-F7-44-41-A7-2E-51-13-98-5C-98-A9-DB-84-CD-4B-52-69-0D-CD-F8-8A-2D-82-FF-7E-A2-9B-88-1E-AB-CE-C4-2C-E3-86-04-DE-F3-D2-E7-7C-94-4A-52-FB-03-F9-09-91-46-28-20-1D-19-B9-9F-B2-B4-7E-D0-91-55-B9-D2-BD-93-F6-DE-D3-19-0B-B7-8A-1A-A0-20-6E-1A-A0-AC-30-A9-1E-D1-D0-C2-A6-0E-48-78-16-C5-5B-93-8D-47-BB-D2-A3-F3-FC-BE-BA-7D-2F-77-32-D0-47-CE-DB-8B-E5-58-B6-EE-D8-C6-40-EE-4A-ED-7B-45-A1-21
BoardId: 26-59-A7-A6-28-87-EB-BF-88-AF-F9-67-F8-F4-D7-03
MainThread: 3169506680
PsiSize:1350694858
NumMacAddr: 2007810619
BaseMacAddr:D5-D3-4E-55-AF-BE
OldCheckSum:2826698910
GponVendorId: 7A-0B-3C-A8
GponVendorSerialNumber: F3-F2-0C-EC-E0-41-19-28-35
GponPassword: ????B<?j?3?
WpsDevPin: AF-71-93-D9-03-8A-F7-5F
WLanParams: 46-6F-68-58-56-DF-38-6B-F4-02-57-4B-1C-4C-19-9A-FA-64-6F-E3-2A-6F-A1-3C-9B-CE-9C-20-39-A9-11-EE-C3-CC-43-DA-43-43-E8-81-23-DE-37-4D-B3-55-D5-54-75-22-34-9B-D1-8C-60-3B-1B-23-5E-AC-1C-DA-1B-52-1F-85-06-0A-71-61-06-A9-E6-2B-1B-1D-A3-98-D3-05-31-C3-3C-1D-3B-01-40-43-A6-41-70-96-8C-C4-AA-D6-7A-26-CB-7A-41-5D-3D-76-41-9F-F9-89-AF-5D-19-AF-5D-19-AF-FE-3A-BE-51-3F-82-0F-E3-AE-E5-10-AD-40-0E-C1-09-E4-10-0B-2C-EF-91-19-4A-7C-BE-5A-91-B0-69-53-12-AF-24-F6-32-16-CF-50-C2-C8-BC-CF-22-1F-71-1A-15-E7-08-E8-A8-E1-51-4C-18-A3-45-0B-42-A2-A9-1B-EA-78-C1-29-23-01-09-B9-70-56-D2-18-69-EF-21-75-11-E3-4F-34-F6-C8-7C-AB-86-FE-83-09-A8-04-0F-56-09-F7-4A-D8-90-5D-3E-80-C3-08-8B-73-53-A2-1D-DB-83-56-A3-99-29-7A-CF-1A-1C-14-E6-4B-00-D9-2A-81-0C-74-81-94-59-F8-43-A8-A8-38-20-B1-B8-B8
SyslogSize: 1019152545
NandPartOfsKb: 210465093
NandPartSizeKb: 2341503706
VoiceBoardId: 22-33-17-E1-73-0B-33-13-03-6C-E6-02-E3-27-20-D8
AfeId: 1B-1E-29-D8-FC-0C-56-E1
Checksum: 2807901263
crc: 210603001

**Comment by mjrr15** [comment]
Attached is a zip file with the dump from the device.

[fw-11112021-011001.zip](https://github.com/Unifi-Tools/UFiber.Configurator/files/7520622/fw-11112021-011001.zip)

**Comment by mjrr15** [comment]
@galvesribeiro  Went through the code and then noticed you already had a way to output the NVRAM info to the console, so the below might (hopefully) prove a bit more useful.

--- NVRAM Information --
- mtdblock3 hash: 6fe87f35fbc1afa6c784ad0da3ed6c67d966dc617eb5327a27b4bee70e7f6900
- NVRAM Version: 4294967295
- Boot parameters: ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
- Board Id: ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
- PSI size: 4294967295
- Total MAC addresses: 4294967295
- GPON MAC address: FF:FF:FF:FF:FF:FF
- GPON Vendor Id: ????
- GPON Serial Number: ÿÿÿÿÿÿÿÿÿ
- GPON SLID (password): ???????????
- Checksum: 4294967295
- crc: 2575180008

**Comment by mjrr15** [comment]
Assume the problem might be the device is using a different chipset than the LOCO or Nano G (see below).

# cat /proc/version 
Linux version 3.18.24 (builder@495832364b50) (gcc version 4.8.5 20150209 (prerelease) (Realtek MSDK-4.8.5p1 Build 2536) ) #1 SMP Thu Apr 15 08:09:10 UTC 2021 [luna SDK V3.2.0]

# lsmod
    Tainted: P  
rlt_wifi 1446693 1 - Live 0xc03de000
europa_drv 50008 0 - Live 0xc01f9000 (PO)
rtk_tr142 23894 0 - Live 0xc01dc000 (O)
pf_rg 75385 1 rtk_tr142, Live 0xc01b7000 (O)
omcidrv 55896 1 pf_rg, Live 0xc0184000 (O)
ubnthal 10003 0 - Live 0xc0168000 (PO)

# lspci -k
00:00.0 Class 0604: 10ec:8196
00:01.0 Class 0280: 14c3:7603 mt_drv

# ls /lib/modules/3.18.24/kernel/drivers/net/ethernet/realtek/ -la
drwxr-xr-x    3 ubnt     0               26 Apr 15  2021 rtl86900
-rw-r--r--    1 ubnt     0            40886 Apr 15  2021 re8686_rtl9607c_test.ko
drwxr-xr-x    3 ubnt     0               30 Apr 15  2021 ..
drwxr-xr-x    3 ubnt     0               62 Apr 15  2021 .


# ls /lib/modules/3.18.24/kernel/drivers/net/wireless/mediatek/rlt_wifi_ap/rlt_wifi.ko -la
-rw-r--r--    1 ubnt     0          1905166 Apr 15  2021 /lib/modules/3.18.24/kernel/drivers/net/wireless/mediatek/rlt_wifi_ap/rlt_wifi.ko

# ls /lib/modules/3.18.24/kernel/drivers/net/ethernet/realtek/rtl86900/sdk/src/module/* -la
/lib/modules/3.18.24/kernel/drivers/net/ethernet/realtek/rtl86900/sdk/src/module/epon_drv:
drwxr-xr-x    2 ubnt     0               34 Apr 15  2021 .
drwxr-xr-x    5 ubnt     0               68 Apr 15  2021 ..
-rw-r--r--    1 ubnt     0            15667 Apr 15  2021 epon_drv.ko

/lib/modules/3.18.24/kernel/drivers/net/ethernet/realtek/rtl86900/sdk/src/module/epon_mpcp:
drwxr-xr-x    2 ubnt     0               35 Apr 15  2021 .
drwxr-xr-x    5 ubnt     0               68 Apr 15  2021 ..
-rw-r--r--    1 ubnt     0            19499 Apr 15  2021 epon_mpcp.ko

/lib/modules/3.18.24/kernel/drivers/net/ethernet/realtek/rtl86900/sdk/src/module/epon_polling:
drwxr-xr-x    2 ubnt     0               38 Apr 15  2021 .
drwxr-xr-x    5 ubnt     0               68 Apr 15  2021 ..
-rw-r--r--    1 ubnt     0             9448 Apr 15  2021 epon_polling.ko

# ls /lib/modules/3.18.24/kernel/drivers/net/wireless/mediatek/rlt_wifi_ap/rlt_wifi.ko -la
-rw-r--r--    1 ubnt     0          1905166 Apr 15  2021 /lib/modules/3.18.24/kernel/drivers/net/wireless/mediatek/rlt_wifi_ap/rlt_wifi.ko

# ls /lib/modules/ -la
drwxr-xr-x    4 ubnt     0              260 Apr 15  2021 .
drwxr-xr-x    7 ubnt     0             2180 Apr 15  2021 ..
drwxr-xr-x    3 ubnt     0               87 Apr 15  2021 3.18.24
-rw-r--r--    1 ubnt     0            15667 Apr 15  2021 epon_drv.ko
-rw-r--r--    1 ubnt     0            19499 Apr 15  2021 epon_mpcp.ko
-rw-r--r--    1 ubnt     0             9448 Apr 15  2021 epon_polling.ko
-rw-r--r--    1 ubnt     0           531676 Apr 15  2021 europa_drv.ko
-rw-r--r--    1 ubnt     0            73120 Apr 15  2021 europa_drv_8290.ko
drwxr-xr-x    2 ubnt     0              196 Apr 15  2021 features
-rw-r--r--    1 ubnt     0            79377 Apr 15  2021 omcidrv.ko
-rw-r--r--    1 ubnt     0            51013 Apr 15  2021 pf_fc.ko
-rw-r--r--    1 ubnt     0           110317 Apr 15  2021 pf_rg.ko
-rw-r--r--    1 ubnt     0           197436 Apr 15  2021 pf_rtk.ko
-rw-r--r--    1 ubnt     0            39274 Apr 15  2021 rtk_tr142.ko
-rw-r--r--    1 ubnt     0            18018 Apr 15  2021 ubnthal.ko

**Comment by mjrr15** [comment]
Been trying to understand the dump, but first time looking at the HEX editor, so trying to make sense and understand things. Any guidance or suggestion would be appreciated.

**Comment by headincl0ud** [comment]
Same issue here

**Comment by Minzdravv** [comment]
please improve the configurator for ufiber wifi
[fw-11112021-011001.zip](https://github.com/Unifi-Tools/UFiber.Configurator/files/14893318/fw-11112021-011001.zip)

**Comment by swas** [comment]
Hello!

Any progress with this?

Thanks!
